# Configuration for the labeler action
# https://github.com/actions/labeler

# BMAD Method related labels
'bmad/core':
  - '.bmad-core/**/*'
  - '.cursor/rules/bmad/**/*'

'bmad/docs':
  - 'docs/prd/**/*'
  - 'docs/architecture/**/*'
  - 'docs/stories/**/*'
  - 'docs/qa/**/*'

'bmad/workflows':
  - '.github/workflows/**/*'

# Technology stack labels
'tech/frontend':
  - 'src/components/**/*'
  - 'src/pages/**/*'
  - 'src/hooks/**/*'
  - 'public/**/*'
  - '**/*.css'
  - '**/*.scss'
  - '**/*.less'

'tech/backend':
  - 'src/api/**/*'
  - 'src/services/**/*'
  - 'src/models/**/*'
  - 'src/controllers/**/*'
  - 'src/middleware/**/*'

'tech/database':
  - 'src/database/**/*'
  - 'src/migrations/**/*'
  - 'src/seeds/**/*'
  - '**/*migration*'
  - '**/*schema*'

'tech/docker':
  - 'Dockerfile'
  - 'docker-compose*.yml'
  - '.dockerignore'
  - 'docker/**/*'

'tech/testing':
  - '**/*.test.*'
  - '**/*.spec.*'
  - 'tests/**/*'
  - 'test/**/*'
  - '__tests__/**/*'
  - 'cypress/**/*'
  - 'e2e/**/*'

# Documentation labels
'documentation':
  - '**/*.md'
  - 'docs/**/*'

# Configuration labels
'config':
  - '*.json'
  - '*.yml'
  - '*.yaml'
  - '*.toml'
  - '.env*'
  - '.*rc*'
  - '*.config.*'

# Dependencies labels
'dependencies':
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'pnpm-lock.yaml'

# CI/CD labels
'ci/cd':
  - '.github/**/*'
  - '.gitlab-ci.yml'
  - 'Jenkinsfile'
  - 'azure-pipelines.yml'

# Security labels
'security':
  - '**/*security*'
  - '**/*auth*'
  - '**/*encrypt*'
  - '**/*token*'
  - '**/*secret*'
