# AAEConnect Prometheus Configuration
# Advanced ID Asia Engineering Co.,Ltd
# Real-time performance monitoring for enterprise communication platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aaeconnect-monitor'
    company: 'Advanced ID Asia Engineering'
    location: 'Chiang Mai, Thailand'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rules for performance targets
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # AAEConnect Backend Metrics
  - job_name: 'aaeconnect-backend'
    static_configs:
      - targets: ['backend:9090']
        labels:
          service: 'backend'
          env: 'production'
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node.js Application Metrics
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['backend:3000']
        labels:
          app: 'aaeconnect'
          type: 'nodejs'

  # PostgreSQL Metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          database: 'postgresql'
          role: 'primary'

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          cache: 'redis'
          cluster: 'main'

  # TimescaleDB Metrics
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescale-exporter:9187']
        labels:
          database: 'timescaledb'
          type: 'time-series'

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          monitor: 'containers'

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          monitor: 'system'

  # Matrix Synapse Metrics
  - job_name: 'matrix-synapse'
    static_configs:
      - targets: ['matrix:9000']
        labels:
          service: 'matrix'
          encryption: 'e2e'
    metrics_path: '/_synapse/metrics'

  # MinIO Object Storage Metrics
  - job_name: 'minio'
    bearer_token: 'AAE@Minio#Token$2025'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
        labels:
          storage: 'minio'

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
          dashboard: 'monitoring'

# Performance alerts based on AAE targets
# Alert if latency > 25ms, memory > 25MB, etc.
